---

# Creates a user for jenkins with the correct ssh key retrieved from the secrets
# repository
#
- name: Gather facts
  action: ec2_facts
  tags: ['jenkins', 'hosts', 'mesos', 'jenkins_config']

- name: create user for jenkins
  user: name=jenkins
    comment="Jenkins CI"
    home="/var/lib/jenkins"
    shell="/bin/bash"
  tags: ['jenkins']

- name: make sure /var/lib/jenkins/.ssh exists
  file: path=/var/lib/jenkins/.ssh
    owner=jenkins
    group=jenkins
    mode=0700
    state=directory
  tags: ['jenkins']

# we don't have enough space for logs in the / filesystem so we dump our logs
# to the EBS volume
# - name: symlink /var/log/jenkins to /data/jenkins.log
#   file: dest=/var/log/jenkins/jenkins.log
#     src=/data/jenkins.log
#     owner=jenkins
#     group=jenkins
#     state=link
#     force=True
#   tags: logs

# We install a specific version of jenkins to avoid compability
# issues with plugins
#
- name: unlock jenkins version in yum
  lineinfile: dest=/etc/yum/pluginconf.d/versionlock.list
    state=absent
    regexp='^.:jenkins-.*'
  tags: ['jenkins', 'versionlock']

# checks to see if jenkins is installed
# if (installed AND current version is not the configured version)
#   uninstall
# endif
# then ensures configured version is installed
- name: is jenkins currently installed?
  command: rpm -q jenkins
  register: is_jenkins_installed
  ignore_errors: True
  tags: ['jenkins', 'versionlock']

- name: check the current jenkins version (if already installed)
  shell: "rpm -q jenkins --queryformat '%{version}-%{release}'"
  register: jenkins_installed_version
  ignore_errors: True
  when: is_jenkins_installed.stdout.find('is not installed') == -1
  tags: ['jenkins', 'versionlock']

- name: uninstall jenkins if installed version not equal to configured version (notifies restart)
  yum: name=jenkins state=absent
  when: ( is_jenkins_installed.stdout.find('is not installed') == -1 ) and  
        ( azulinho_jenkins_server['version'] != jenkins_installed_version.stdout)
  tags: ['jenkins', 'versionlock']
  notify:
    - restart jenkins

- name: install specified version of jenkins
  yum: name=http://pkg.jenkins-ci.org/redhat-stable/jenkins-{{ azulinho_jenkins_server['version']}}.noarch.rpm
  tags: ['jenkins', 'versionlock']

- name: lock jenkins
  command: yum versionlock jenkins-{{ azulinho_jenkins_server['version'] }}
  tags: ['jenkins', 'versionlock']

# configure jenkins to our liking
#
- name: Configure Jenkins Port
  sudo: yes
  when: azulinho_jenkins_server['port'] is defined
  lineinfile: dest=/etc/default/jenkins
    regexp=^HTTP_PORT=
    line=HTTP_PORT={{ azulinho_jenkins_server['port'] }}
    create=yes
  tags: ['jenkins']
  notify:
    - safe-restart jenkins

- name: get iptable rules
  shell: iptables -L
  register: iptablesrules
  sudo: yes
  tags: ['jenkins', 'firewall', 'jenkins_port']

- name: add jenkins rule for jenkins port
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ azulinho_jenkins_server['port'] }} -j ACCEPT -m comment --comment "Jenkins"
  when: iptablesrules.stdout.find("Jenkins") == -1
  sudo: yes
  tags: ['jenkins', 'firewall', 'jenkins_port']

- name: add jenkins firewall rule for mesos slaves
  command: /sbin/iptables -I INPUT 2 -p tcp --match multiport --dports 1024:65535 -j ACCEPT -m comment --comment "Mesos Slaves"
  when: iptablesrules.stdout.find("Mesos") == -1
  sudo: yes
  tags: ['jenkins', 'firewall', 'jenkins_port']

- name: save iptables
  command: service iptables save
  sudo: yes
  tags: ['jenkins', 'firewall', 'jenkins_port']

- name: restart iptables
  service: name=iptables state=restarted
  sudo: yes
  tags: ['jenkins', 'firewall', 'jenkins_port']

- name: Configure Jenkins Prefix
  sudo: yes
  when: azulinho_jenkins_server['prefix'] is defined
  lineinfile: dest=/etc/default/jenkins
    regexp=^PREFIX=
    line=PREFIX={{ azulinho_jenkins_server['prefix'] }}
  tags: ['jenkins']
  notify:
    - safe-restart jenkins

- name: Configure Jenkins E-mail
  sudo: yes
  when: azulinho_jenkins_server['email'] is defined
  template: src=hudson.tasks.Mailer.xml.j2
    dest={{ azulinho_jenkins_server['lib'] }}/hudson.tasks.Mailer.xml
    owner=jenkins
    group=jenkins
    mode=0644
  tags: ['jenkins']
  notify:
    - safe-restart jenkins

- name: Deploy main jenkins config.xml file
  template: dest=/var/lib/jenkins/config.xml
    src=config.xml.j2
  tags: ['jenkins', 'jenkins_config']
  notify:
    - safe-restart jenkins

- name: update jenkins main config.xml file
  file: path=/var/lib/jenkins/config.xml
        state=file
        owner=jenkins
        group=jenkins
  tags: ['jenkins', 'jenkins_config']
  notify:
    - safe-restart jenkins

- name: Deploy GlobalStats plugin config
  template: dest=/var/lib/jenkins/org.jenkinsci.plugins.statsd.StatsdConfig.xml
    src=org.jenkinsci.plugins.statsd.StatsdConfig.xml.j2
  tags: ['jenkins', 'jenkins_config']
  notify:
    - safe-restart jenkins

- name: update jenkins GlobalStats plugin config
  file: path=/var/lib/jenkins/org.jenkinsci.plugins.statsd.StatsdConfig.xml
        state=file
        owner=jenkins
        group=jenkins
  tags: ['jenkins', 'jenkins_config']
  notify:
    - safe-restart jenkins

# Configure files to be deployed to the slaves
- name: Create /etc/slave_config
  file: path=/etc/slave_config
    owner=jenkins
    group=jenkins
    mode=0700
    state=directory
  tags: ['jenkins', 'jenkins_config']

- name: Copy config contents of acceptance.yaml to config dir
  copy: content="{{ acceptance.config }}"
    dest=/etc/slave_config/acceptance.yaml
  tags: ['jenkins', 'jenkins_config']

- name: Copy ssh key contents of acceptance.yaml to slave dir
  copy: content="{{ acceptance['ssh-key'] }}"
    dest=/etc/slave_config/id_rsa
  tags: ['jenkins', 'jenkins_config']

- name: add devpi caching server to the environment
  copy: content="export PIP_INDEX_URL=http://{{devpi['host']}}:{{devpi['port']}}/root/pypi/+simple/; export TRUSTED_HOST={{devpi['host']}}"
    dest=/etc/slave_config/pip.sh
  tags: ['jenkins', 'jenkins_config']

- name: add s3 clusterhq-dev-archive credentials to /etc/slave_config
  copy: content="export S3_BUCKET={{s3_clusterhq_dev_archive['bucket_name']}}; export AWS_ACCESS_KEY_ID={{s3_clusterhq_dev_archive['aws_access_key_id']}} ; export AWS_SECRET_KEY_ID={{s3_clusterhq_dev_archive['aws_secret_access_key']}}"
    dest=/etc/slave_config/s3_dev_archive_clusterhq.com
  tags: ['jenkins', 'jenkins_config', 'jenkins_secrets']

- name: add s3 clusterhq-vagrant-jenkins_boxes credentials to /etc/slave_config
  copy: content="export S3_BUCKET={{s3_clusterhq_vagrant_jenkins_boxes['bucket_name']}}; export AWS_ACCESS_KEY_ID={{s3_clusterhq_vagrant_jenkins_boxes['aws_access_key_id']}} ; export AWS_SECRET_KEY_ID={{s3_clusterhq_vagrant_jenkins_boxes['aws_secret_access_key']}}"
    dest=/etc/slave_config/s3_vagrant_jenkins_boxes_clusterhq.com
  tags: ['jenkins', 'jenkins_config', 'jenkins_secrets']

- name: add github credentials file
  copy: content="export GITHUB_STATUS_USERNAME=http://{{github_jenkins_credentials['username']}}; export GITHUB_STATUS_API_TOKEN={{github_jenkins_credentials['api_token']}}; export JENKINS_URL={{azulinho_jenkins_server['jenkins_url']}}"
    dest=/etc/slave_config/github_status.sh
  tags: ['jenkins', 'jenkins_config', 'github_status']

- name: copy /etc/sysconfig/docker for centos7 to /etc/slave_config
  template: dest=/etc/slave_config/docker.centos7
    src=docker.centos7.j2
  tags: ['jenkins', 'jenkins_config']

- name: copy /etc/default/docker for ubuntu 14 to /etc/slave_config
  template: dest=/etc/slave_config/docker.ubuntu14
    src=docker.ubuntu14.j2
  tags: ['jenkins', 'jenkins_config']

- name: create dockerhub creds file in /etc/slave_config
  copy: dest=/etc/slave_config/dockerhub_creds
    content="{{ credentials['dockerhub']['user']}}:{{ credentials['dockerhub']['password']}}:{{credentials['dockerhub']['email']}}"
  tags: ['jenkins', 'jenkins_config', 'jenkins_secrets']

- name: deploy jenkins-slave private key to /etc/slave_config
  copy: dest=/etc/slave_config/jenkins-slave.ssh.private_key
    content="{{ cloud_pem_keys['jenkins_slave_private_key'] | join('\n') }}"
  tags: ['jenkins', 'jenkins_config', 'jenkins_slave_setup', 'jenkins_secrets']

- name: Deploy jenkins slave-setup config
  template: dest=/var/lib/jenkins/org.jenkinsci.plugins.slave_setup.SetupConfig.xml
    src=org.jenkinsci.plugins.slave_setup.SetupConfig.xml.j2
  tags: ['jenkins', 'jenkins_config', 'jenkins_slave_setup']
  notify:
    - safe-restart jenkins

- name: Deploy jenkins slave init script
  template: dest=/etc/slave_config/CommandLineScript.sh
    src=CommandLineScript.sh.j2
  tags: ['jenkins', 'jenkins_config', 'jenkins_slave_setup']
  notify:
    - safe-restart jenkins

- name: Deploy github token file
  template: dest=/var/lib/jenkins/.github_token
    src=github_token.j2
  tags: ['jenkins', 'jenkins_config']
  notify:
    - safe-restart jenkins

- name: Deploy AWS UFT terraform file
  template: dest=/etc/slave_config/get_aws_credentials_uft.sh
    src=get_aws_credentials_uft.sh.j2
  tags: ['jenkins', 'jenkins_config', 'uft']
  notify:
    - safe-restart jenkins

- name: Deploy nodeMonitors file
  template: dest=/var/lib/jenkins/nodeMonitors.xml
    src=nodeMonitors.xml.j2
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files']
  notify:
    - safe-restart jenkins

- name: increase jenkins JVM heap-size
  lineinfile:
    dest=/etc/sysconfig/jenkins
    line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Xmx8192m -Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000 "'
    state=present
  tags: ['jenkins', 'jenkins_config', 'jenkins_jvm']
  notify:
  notify:
    - safe-restart jenkins

- name: Create jenkins users directories
  file: dest={{ azulinho_jenkins_server['lib'] }}/users
    state=directory
    owner=jenkins
    group=jenkins
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'jenkins_users']

# Deploy the jenkins users
- name: Create jenkins users directories
  file: dest={{ azulinho_jenkins_server['lib'] }}/users/{{item['username']}}
    state=directory
    owner=jenkins
    group=jenkins
  with_items: azulinho_jenkins_server['users']
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'jenkins_users']

# This is reallly really ugly, we need a lookup plugin
#- name: Expand the users with encrypted API token string
  #shell: "echo {{item['username']}} $(java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }}/ groovy {{ azulinho_jenkins_server['lib'] }}/ReturnJenkinsEncryptedString.groovy {{ item['apiToken'] }} )"
  #tags: ['jenkins', 'jenkins_config', 'cloudbees']
  #with_items: azulinho_jenkins_server['users']
  #register: expanded_jenkins_users_passwords_api_token
  #tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'jenkins_users']
  #notify:
    #- safe-restart jenkins

- name: Deploy the jenkins users config files
  template: dest={{ azulinho_jenkins_server['lib'] }}/users/{{ item['username'] }}/config.xml
    src=do_jenkinsUser.xml.j2
    owner=jenkins
    group=jenkins
  with_items: azulinho_jenkins_server['users']
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'jenkins_users']
  notify:
    - safe-restart jenkins

# Start jenkins, we need it up and running before we are able to download
# the CLI tool
- name: Ensure jenkins is running
  service: name=jenkins
    enabled=yes
    state=running
  tags: ['jenkins', 'initscripts']

# If Jenkins is installed or updated, wait for pulling the Jenkins CLI
# # wish there was a jenkins-cli rpm package
#
- name: Wait for Jenkins to start up before proceeding.
  shell: "curl -D - --silent http://{{ azulinho_jenkins_server['user'] }}:{{ azulinho_jenkins_server['apiToken'] }}@localhost:{{ azulinho_jenkins_server['port'] }}/cli/"
  register: result
  until: (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: 300
  delay:  1
  changed_when: false

# Create Jenkins CLI destination directory
- name: "Create Jenkins CLI destination directory"
  file: path={{ azulinho_jenkins_server['dest'] }}
    state=directory
  sudo: yes
  tags: ['jenkins', 'jenkinscli']

# Get Jenkins CLI from localhost
- name: Get Jenkins CLI
  get_url: url=http://localhost:{{ azulinho_jenkins_server['port'] }}/jnlpJars/jenkins-cli.jar
    dest={{ azulinho_jenkins_server['cli_dest'] }}
    mode=0440
  sudo: yes
  tags: ['jenkins', 'jenkinscli']

# Login usin the CLI
- name: Login to Jenkins using CLI
  shell: java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }} login --username {{ azulinho_jenkins_server['user'] }} --password {{ azulinho_jenkins_server['password'] }}
  tags: ['jenkins', 'jenkins_config']

# Lets deploy the Credentials file,
# Jenkins encrypts the passwords locally on the server based on a couple of
# local files, this means we can't store an encrypted password in our secrets.
# We can however use a jenkins Java library to retrieve the encrypted hash
# that we need to insert into our credentials.xml file.
# For that Jenkins needs to be running,  as we need to retrieve the encrypted
# password from jenkins using a groovy script
#
- name: Deploy groovy script file for retrieving jenkins encrypted strings
  template: dest={{ azulinho_jenkins_server['lib'] }}/ReturnJenkinsEncryptedString.groovy
    src=ReturnJenkinsEncryptedString.groovy
    owner=jenkins
    group=jenkins
  tags: ['jenkins', 'jenkins_config', 'jenkins_users']

- name: Deploy groovy script file for retrieving cloudbees password
  template: dest={{ azulinho_jenkins_server['lib'] }}/cloudbees.groovy
    src=cloudbees.groovy.j2
    owner=jenkins
    group=jenkins
  tags: ['jenkins', 'jenkins_config', 'cloudbees']
  notify:
    - safe-restart jenkins

- name: Deploy groovy script file for retrieving github_pr secret
  template: dest={{ azulinho_jenkins_server['lib'] }}/github_pr.groovy
    src=github_pr.groovy.j2
    owner=jenkins
    group=jenkins
  tags: ['jenkins', 'jenkins_config', 'github_pr']
  notify:
    - safe-restart jenkins

- name: Retrieve the CloudBees password from Jenkins
  shell: java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }}/ groovy {{ azulinho_jenkins_server['lib'] }}/cloudbees.groovy
  tags: ['jenkins', 'jenkins_config', 'cloudbees']
  register: cloudbees_encrypted_password
  notify:
    - safe-restart jenkins

- name: Retrieve the github_pr secret from Jenkins
  shell: java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }}/ groovy {{ azulinho_jenkins_server['lib'] }}/github_pr.groovy
  tags: ['jenkins', 'jenkins_config', 'github_pr']
  register: github_pr_secret
  notify:
    - safe-restart jenkins

- name: Remove the cloudbees groovy file
  file: path={{ azulinho_jenkins_server['lib'] }}/cloudbees.groovy
    state=absent
  tags: ['jenkins', 'jenkins_config', 'cloudbees']
  notify:
    - safe-restart jenkins

- name: Remove the github_pr groovy file
  file: path={{ azulinho_jenkins_server['lib'] }}/github_pr.groovy
    state=absent
  tags: ['jenkins', 'jenkins_config', 'github_pr']
  notify:
    - safe-restart jenkins

- name: Deploy Credentials File
  template: dest={{ azulinho_jenkins_server['lib'] }}/credentials.xml
    src=credentials.xml.j2
    owner=jenkins
    group=jenkins
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'cloudbees']
  notify:
    - safe-restart jenkins

# Deploy the CloudBees Slave Configuration templates
# we use these to specify which size our slaves should be
- name: Create cloudbees CloudSlaveTemplates dir
  file: dest={{ azulinho_jenkins_server['lib'] }}/cloudSlaveTemplates/{{item['label']}}
    state=directory
    owner=jenkins
    group=jenkins
  with_items: azulinho_jenkins_server['clouds']['cloudbees_cloud_connector_plugin']['templates']
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'cloudbees']
  notify:
    - safe-restart jenkins

- name: Deploy CloudBees Slave Template configs
  template: dest={{ azulinho_jenkins_server['lib'] }}/cloudSlaveTemplates/{{ item.label }}/config.xml
    src=cloudSlaveTemplates.j2
    owner=jenkins
    group=jenkins
  with_items: azulinho_jenkins_server['clouds']['cloudbees_cloud_connector_plugin']['templates']
  tags: ['jenkins', 'jenkins_config', 'xml_conf_files', 'cloudbees']
  notify:
    - safe-restart jenkins


# add hostname to /etc/hosts
# this is needed by the mesos_cloud plugin.
- name: Add hostname entry to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='{{ansible_ec2_public_ipv4}} {{ ansible_hostname }}'
  tags: ['jenkins', 'hosts', 'mesos']

