---
- hosts: jenkins_servers
  max_fail_percentage: 1
  serial: 1
  sudo: true
  vars:
    # resmo/ansible-role-fail2ban
    fail2ban_config_jail_ssh_enabled: no
    fail2ban_config_jail_sshddos_enabled: no

    sysctl_config:
      # Protection from SYN flood attack
      net.ipv4.tcp_syncookies: 1
      # See evil packets in your logs
      net.ipv4.conf.all.log_martians: 1
      # Increase number of incoming connections that can queue up before
      # dropping
      net.core.somaxconn: 50000
      # Handle SYN floods and large numbers of valid HTTPS connections
      net.ipv4.tcp_max_syn_backlog: 30000
      # Increase the length of the network device input queue
      net.core.netdev_max_backlog: 5000
      # Increase system file descriptor limit
      fs.file-max: 100000
      # Widen the port range used for outgoing connections
      net.ipv4.ip_local_port_range: 3000 65000
      # Disable source routing and redirects
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      # Disable packet forwarding.
      net.ipv4.ip_forward: 0
      net.ipv6.conf.all.forwarding: 0

      # Disable TCP slow start on idle connections
      net.ipv4.tcp_slow_start_after_idle: 0

      # Disconnect dead TCP connections after 1 minute
      net.ipv4.tcp_keepalive_time: 60
      # Allow a high number of timewait sockets
      net.ipv4.tcp_max_tw_buckets: 2000000
      # Timeout broken connections faster
      net.ipv4.tcp_fin_timeout: 10
      # Let the networking stack reuse TIME_WAIT connections when it thinks it's
      # safe to do so
      net.ipv4.tcp_tw_reuse: 1
      # Determines the wait time between isAlive interval probes
      net.ipv4.tcp_keepalive_intvl: 15
      # Determines the number of probes before timing out
      net.ipv4.tcp_keepalive_probes: 5

      # Increase Linux autotuning TCP buffer limits
      net.core.rmem_max: 16777216
      net.core.wmem_max: 16777216
      net.core.rmem_default: 16777216
      net.core.wmem_default: 16777216
      net.core.optmem_max: 40960
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_wmem: 4096 65536 16777216

  pre_tasks:
    - name: gather ec2 facts
      action: ec2_facts
      tags:
        - facts
        - always

  roles:
    # disable selinux, required on aws
    - local.disable_selinux

    # set pam.d limits.conf
    - local.set_pam_limits

    # configure /etc/resolv.conf
    - Azulinho.azulinho-google-dns

    # Install OS updates
    - local.updates

    # TODO: this is breaking our run
    # configure ntp
    # - bennojoy.ntp

    # install latest git
    - local.latest-git

    # jenkins role installs jenkins
    - local.Azulinho.azulinho-jenkins-server

    # deploy S3 credentials to the staging-docs bucket
    - local.deploy_aws_s3_docs_staging_creds

    - local.build-mesos-native-library

      # jenkins-plugins role installs the jenkins-plugins
    - local.Azulinho.azulinho-jenkins-plugins

    # deploy SSH keys
    - Azulinho.azulinho-ssh-keys

    # deploy render.py file
    - local.render-jobs-file

    # deploy jenkins-to-graphite.py script
    - local.jenkins-to-graphite

    # deploy jobs using the groovy DSL
    - local.Azulinho.azulinho-jenkins-reconfigure-jobs-using-job-dsl

    # deploy the groovy interpreter
    - local.deploy_groovy

    # apply fail2ban
    - resmo.fail2ban

    # apply sysctl settings
    - jtyr.sysctl
