---
- hosts: jenkins_servers
  max_fail_percentage: 1
  serial: 1
  sudo: true

  roles:
    # disable selinux, required on aws
    - local.disable_selinux

    # configure /etc/resolv.conf
    - Azulinho.azulinho-google-dns

    # Install OS updates
    - local.updates

    # TODO: this is breaking our run
    # configure ntp
    # - bennojoy.ntp

    # install latest git
    - local.latest-git

    # jenkins role installs jenkins
    - local.Azulinho.azulinho-jenkins-server

      # jenkins-plugins role installs the jenkins-plugins
    - local.Azulinho.azulinho-jenkins-plugins

    # deploy SSH keys
    - Azulinho.azulinho-ssh-keys

    # deploy render.py file
    - local.render-jobs-file

    # deploy jobs using the groovy DSL
    - local.Azulinho.azulinho-jenkins-reconfigure-jobs-using-job-dsl

