---
- hosts: jenkins_servers
  max_fail_percentage: 1
  serial: 1
  sudo: true

  pre_tasks:
    - name: gather ec2 facts
      action: ec2_facts
      tags:
        - facts
        - always

  roles:

    # install swapfile
    - local.swapfile

    # install latest kernel
    - local.elrepo-kernel

    # disable selinux, required on aws
    - local.disable_selinux

    # set pam.d limits.conf
    - local.set_pam_limits

    # configure /etc/resolv.conf
    - Azulinho.azulinho-google-dns

    # Install OS updates
    - local.updates

    # TODO: this is breaking our run
    # configure ntp
    # - bennojoy.ntp

    # install latest git
    - local.latest-git

    # jenkins role installs jenkins
    - local.Azulinho.azulinho-jenkins-server

    # deploy S3 credentials to the staging-docs bucket
    - local.deploy_aws_s3_docs_staging_creds

    - local.build-mesos-native-library

      # jenkins-plugins role installs the jenkins-plugins
    - local.Azulinho.azulinho-jenkins-plugins

    # deploy SSH keys
    - Azulinho.azulinho-ssh-keys

    # deploy render.py file
    - local.render-jobs-file

    # deploy jenkins-to-graphite.py script
    - local.jenkins-to-graphite

    # deploy jobs using the groovy DSL
    - local.Azulinho.azulinho-jenkins-reconfigure-jobs-using-job-dsl

    # deploy the groovy interpreter
    - local.deploy_groovy

