# deploys groovy from the groovy website
#
#
- name: Fetch stable groovy
  get_url: url=https://bintray.com/artifact/download/groovy/maven/apache-groovy-binary-2.4.5.zip
    dest=/root/
  tags: groovy

- name: Install Groovy
  command: unzip /root/apache-groovy-binary-2.4.5.zip
    chdir=/opt
    creates=/opt/groovy-2.4.5
  tags: groovy

- name: symlink groovy to /usr/bin
  file: dest=/usr/bin/groovy
    src=/opt/groovy-2.4.5/bin/groovy
    state=link
  tags: groovy
