---

- name: copy render.py
  copy: dest=/usr/local/bin/render.py
    src=render.py
    owner=jenkins
    group=jenkins
  tags: ['jenkins_render.py']

- name: install jinja2 and yaml
  pip: name={{ item }} executable=/usr/local/bin/pip2.7
  with_items:
    - jinja2
    - pyyaml
  tags: ['jenkins_render.py']
