- name: restart jenkins
  service: name=jenkins state=restarted

- name: Reload jenkins configuration from disk
  shell: java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }} safe-restart

# Safe-restart Jenkins
- name: safe-restart jenkins
  sudo: yes
  shell: java -jar {{ azulinho_jenkins_server['cli_dest'] }} -s http://localhost:{{ azulinho_jenkins_server['port'] }} safe-restart
