---
- name: (RedHat) install ELRepo key
  when: ansible_os_family == "RedHat"
  rpm_key:
    state=present
    key='https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'

- name: (RedHat) install ELRepo
  when: ansible_os_family == "RedHat"
  yum:
    state=present
    name='http://www.elrepo.org/elrepo-release-6-6.el6.elrepo.noarch.rpm'


- name: uninstall distro kernel
  when: ansible_os_family == "RedHat"
  shell: rpm -q {{ item }} && rpm -e --nodeps {{item}}
  with_items:
    - kernel
    - kernel-devel
    - kernel-headers
  ignore_errors: True

- name: install latest kernel
  when: ansible_os_family == "RedHat"
  yum:
    state=latest
    enablerepo=elrepo-kernel
    name={{ item }}
  with_items:
    - kernel-ml
    - kernel-ml-devel
    - kernel-ml-headers